# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update Angular dependencies in the 'web-app' folder
  - package-ecosystem: "npm"
    directory: "/web-app" # Location of Angular project
    schedule:
      interval: "weekly" # Frequency of dependency updates
    commit-message:
      prefix: "chore"
      include: "scope"

  # Update Spring Boot dependencies in the 'server' folder
  - package-ecosystem: "maven"
    directory: "/server" # Location of Spring Boot project
    schedule:
      interval: "weekly" # Frequency of dependency updates
    commit-message:
      prefix: "chore"
      include: "scope"