name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Install dependencies and run tests
        working-directory: ./server
        run: |
          mvn clean test  # Commande pour nettoyer le projet et lancer les tests Maven

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-*.xml
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for frontend
        working-directory: ./web-app
        run: |
          npm install  # Installer les dépendances du projet Angular

      - name: Run frontend tests (Angular)
        working-directory: ./web-app
        run: |
          npm run test -- --watch=false --browsers=ChromeHeadless  # Exécute les tests Angular en mode headless (sans navigateur GUI)

      - name: Archive frontend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: ./web-app/coverage